version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      DB_USER: root
      DB_PASS: secret
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: datastore
    depends_on:
      - db

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: datastore
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
