apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-db
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore-db
  template:
    metadata:
      labels:
        app: datastore-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root
            - name: MARIADB_DATABASE
              value: datastore
            - name: MARIADB_USER
              value: dsuser
            - name: MARIADB_PASSWORD
              value: secret
          volumeMounts:
            - name: datastore-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: datastore-storage
          persistentVolumeClaim:
            claimName: datastore-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: datastore-db
  namespace: demo
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: datastore-db
