apiVersion: v1
kind: Secret
metadata:
  name: datastore-secret
  namespace: demo
type: Opaque
stringData:
  DB_USER: dsuser
  DB_PASS: secret
  DB_HOST: datastore-db
  DB_PORT: "3306"
  DB_NAME: datastore
