---
- name: Provision dz1 instance
  hosts: dz_project
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - git
          - docker.io
          - curl
          - python3-pip
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Ensure Fail2Ban is enabled and running
      systemd:
        name: fail2ban
        enabled: yes
        state: started
